{% set name = "radioactivedecay" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radioactivedecay-{{ version }}.tar.gz
  sha256: 9bac1f39b4f2b456a330449685256ca0577bbaa371e78f52ae8ab5b3070e3b99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_resources
    - matplotlib-base
    - networkx
    - numpy
    - python >=3.6
    - scipy
    - sympy

test:
  imports:
    - radioactivedecay
  commands:
    - pip check
    - python -m unittest discover
  requires:
    - pip
  source_files:
    - tests/

about:
  home: https://github.com/alexmalins/radioactivedecay
  license: MIT AND LicenseRef-ICRP-07
  license_file: LICENSE
  summary: Radioactive decay calculations in Python
  description: |
    A Python package for radioactive decay modelling that supports 1252
    radionuclides, decay chains, branching, and metastable states.
  doc_url: https://alexmalins.com/radioactivedecay/
  dev_url: https://github.com/alexmalins/radioactivedecay


extra:
  recipe-maintainers:
    - alexmalins
