{% set name = "radioactivedecay" %}
{% set version = "0.4.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radioactivedecay-{{ version }}.tar.gz
  sha256: 323c8dfcacb6e2413e535a963e9b7e72edc96000200a67bb73aaef37e113677d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_resources
    - matplotlib-base
    - networkx
    - numpy
    - python >=3.6
    - scipy
    - setuptools
    - sympy

test:
  imports:
    - radioactivedecay
  commands:
    - pip check
    - python -m unittest discover
  requires:
    - pip
  source_files:
    - tests/

about:
  home: https://github.com/radioactivedecay/radioactivedecay
  license: MIT AND LicenseRef-AMDC AND LicenseRef-ICRP-07
  license_file:
    - LICENSE
    - LICENSE.AMDC
    - LICENSE.ICRP-07
  summary: Radioactive decay calculations in Python
  description: |
    A Python package for radioactive decay modelling that supports 1252
    radionuclides, decay chains, branching, and metastable states.
  doc_url: https://radioactivedecay.github.io
  dev_url: https://github.com/radioactivedecay/radioactivedecay


extra:
  recipe-maintainers:
    - alexmalins
